### ISSUE TITLE
error while read data when I use recipe DBLSTM

### ISSUE THREAD

**Issue by fanlu** [vrenkens/nabu#18]
First, I run the kaldi command run.sh in /kaldi/egs/timit/s5/, and generate the data directory in  /kaldi/egs/timit/s5/, 
Then I copy database.conf from database.cfg in nabu/config/recipes/DBLSTM/TIMIT, and I changed the datafiles = /kaldi/egs/timit/s5/data/train/wav.scp in every section.
At last, I run the ./run train --recipe=config/recipes/DBLSTM/TIMIT --expdir=/timit_train/expdir
But I got some error like 
2018-01-30 06:15:37.005053: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: assertion failed: [sil w ey dx ax l ih dx el w ay l sil]                                                │
         [[Node: validate/validation/evaluate/input_pipeline/read_data/reader_1/StringReader/assert_equal/Assert/Assert = Assert[T=[DT_STRING], summarize=3, _device="/job:local/replica:0/task:0/dev│
ice:CPU:0"](validate/validation/evaluate/input_pipeline/read_data/reader_1/StringReader/assert_equal/All_G279, validate/validation/evaluate/input_pipeline/read_data/reader_1/StringReader/ParseSingl│
eExample/Squeeze_data)]]                                                                                                                                                                             │
2018-01-30 06:15:37.025706: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: assertion failed: [sil ah m ao th sil z ih vcl g z ae vcl d ax l ao ng dh ix cl p ae th r uw ao dx ow z │
vcl g aa r vcl en sil]                                                                                                                                                                               │
         [[Node: train/get_batch/input_pipeline/read_data/reader_1/StringReader/assert_equal/Assert/Assert = Assert[T=[DT_STRING], summarize=3, _device="/job:local/replica:0/task:0/device:CPU:0"](t│
rain/get_batch/input_pipeline/read_data/reader_1/StringReader/assert_equal/All_G315, train/get_batch/input_pipeline/read_data/reader_1/StringReader/ParseSingleExample/Squeeze_data)]]               │
WORKER 0: validating model                                                                                                                                                                           │
2018-01-30 06:15:41.148099: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: PaddingFIFOQueue '_20_validate/validation/evaluate/input_pipeline/batch/padding_fifo_queue' is closed and ha│
s insufficient elements (requested 8, current size 0)                                                                                                                                                │
         [[Node: validate/validation/evaluate/input_pipeline/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_INT32, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:local/replica:0/task:0│
/device:CPU:0"](validate/validation/evaluate/input_pipeline/batch/padding_fifo_queue, validate/validation/evaluate/input_pipeline/batch/n)]]                                                         │
2018-01-30 06:15:41.148127: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: PaddingFIFOQueue '_20_validate/validation/evaluate/input_pipeline/batch/padding_fifo_queue' is closed and ha│
s insufficient elements (requested 8, current size 0)

Traceback (most recent call last):                                                                                                                                                                   │
  File "nabu/scripts/prepare_train.py", line 365, in <module>                                                                                                                                        │
    main(FLAGS.expdir, FLAGS.recipe, FLAGS.mode, FLAGS.computing)                                                                                                                                    │
  File "nabu/scripts/prepare_train.py", line 90, in main                                                                                                                                             │
    expdir=expdir)                                                                                                                                                                                   │
  File "/mnt/mfs/fanlu/nabu/nabu/scripts/train.py", line 85, in train                                                                                                                                │
    tr.train(testing)                                                                                                                                                                                │
  File "/mnt/mfs/fanlu/nabu/nabu/neuralnetworks/trainers/trainer.py", line 776, in train                                                                                                             │
    outputs['increment_step'].run(session=sess)                                                                                                                                                      │
  File "/root/miniconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 537, in __exit__                                                                │
    self._close_internal(exception_type)                                                                                                                                                             │
  File "/root/miniconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 574, in _close_internal                                                         │
    self._sess.close()                                                                                                                                                                               │
  File "/root/miniconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 820, in close                                                                   │
    self._sess.close()                                                                                                                                                                               │
  File "/root/miniconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 941, in close                                                                   │
    ignore_live_threads=True)                                                                                                                                                                        │
  File "/root/miniconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join                                                                          │
    six.reraise(*self._exc_info_to_raise)                                                                                                                                                            │
  File "/root/miniconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 238, in _run                                                                    │
    enqueue_callable()                                                                                                                                                                               │
  File "/root/miniconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1231, in _single_operation_run                                                              │
    target_list_as_strings, status, None)                                                                                                                                                            │
  File "/root/miniconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__                                                                     │
    c_api.TF_GetCode(self.status.status))                                                                                                                                                            │
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [sil w ey dx ax l ih dx el w ay l sil]
What steps did I miss?

**Comment by fanlu** [comment]
([[{'datafiles': '/kaldi/egs/timit/s5/data/train/wav.scp', 'type': 'audio_feature', 'dir': '/mnt/mfs/fanlu/timit_dir/features/train', 'processor_config': 'config/recipes/DBLSTM/TIMIT/feature_proces$
or.cfg'}], [{'datafiles': '/kaldi/egs/timit/s5/data/train/text', 'type': 'string', 'dir': '/mnt/mfs/fanlu/timit_dir/normalized/train', 'processor_config': 'config/recipes/DBLSTM/TIMIT/text_processo$
.cfg'}]], 2)
(3696, '/mnt/mfs/fanlu/timit_dir/features/train/data/file224\t/mnt/mfs/fanlu/timit_dir/normalized/train/data/file224')
(3696, 'fdkn0_si1081-0')
([[{'datafiles': '/kaldi/egs/timit/s5/data/dev/wav.scp', 'type': 'audio_feature', 'dir': '/mnt/mfs/fanlu/timit_dir/features/dev', 'processor_config': 'config/recipes/DBLSTM/TIMIT/feature_processor.$
fg'}], [{'datafiles': '/kaldi/egs/timit/s5/data/dev/text', 'type': 'string', 'dir': '/mnt/mfs/fanlu/timit_dir/normalized/dev', 'processor_config': 'config/recipes/DBLSTM/TIMIT/text_processor.cfg'}]$
, 2)
(400, '/mnt/mfs/fanlu/timit_dir/features/dev/data/file169\t/mnt/mfs/fanlu/timit_dir/normalized/dev/data/file169')
(400, 'mbwm0_si1934-0')
this is the data detail log I printed,Is my data wrong?

**Comment by fanlu** [comment]
Sorry about this,
I solved this problem with changed the num_classes from 39 to 48
